### ISSUE TITLE
VSCode Extension Concourse CI Pipeline Editor - Incorrect type definition for put step

### ISSUE THREAD

**Issue by vmladd** [spring-projects/sts4#1005]
**Describe the bug**
The `put` step allows a user to (optionally) specify the `inputs` key as "all", "detect", or a list of resources.  If the user provides "all" or "detect" then the extension displays the error
```
Expecting a 'Sequence` but found a `Scalar`
```

https://concourse-ci.org/put-step.html

**To Reproduce**
Create a job with a `put` step and specify the `inputs` key as "detect"

**Sample**
```yaml
jobs:
- name: example-job
  plan:
    - put: example-resource
      inputs: detect
```
