### ISSUE TITLE
Add no_get param to Concourse schema

### ISSUE THREAD

**Issue by ThibaultDelaune-pro** [spring-projects/sts4#1017]
# Describe the bug

Concourse CI Pipeline Editor VSCode extensions are falsely reporting a problem with `no_get` param in PUT steps.

## Error message:
Unknown property 'no_get' for type 'PutStep' _vscode-concourse(YamlSchemaProblem)_

# To Reproduce
```yaml
---
jobs:
- put: email
  no_get: true
  params:
    ...
```

# Fix

Please add `no_get` to Concourse schema.

cf. https://concourse-ci.org/put-step.html#schema.put.no_get
