### ISSUE TITLE
java.lang.ClassNotFoundException: org.eclipse.jdt.ls.core.internal.javadoc.JavaElementLinks cannot be found by ...

### ISSUE THREAD

**Issue by JavaHello** [spring-projects/sts4#1229]
**Describe the bug**
An error occurred while editing the application.yml file

**To Reproduce**
Using the latest plug-in of VScode Spring Boot, an error occurred when editing the application.yml file.
```yaml
spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
```

**Sample**
```log
java.lang.ClassNotFoundException: org.eclipse.jdt.ls.core.internal.javadoc.JavaElementLinks cannot be found by org.springframework.tooling.jdt.ls.extension_1.0.0.202403062224
```
https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2986/files#diff-7461a672bafbfc5ad174d6ada61aaf8111bd8cbd7544156ef5679029854452ae
This commit removed JavaElementLinks
