### ISSUE TITLE
URL-Hint does not honor server.servlet.contextPath

### ISSUE THREAD

**Issue by mpapenbr** [spring-projects/sts4#129]
The generated clickable link in the editor for an REST-endpoint does not include the server.servlet.contextPath setting 

Controller:
```@RestController("StationsV1")
@RequestMapping(value="/stations")
public class StationController {
....
  @RequestMapping(value = "/{id}", method = RequestMethod.GET)  
  public @ResponseBody HttpEntity<StationResource> getStation(@PathVariable long id) {
  ...
  }
}
```

application.yml:
```
spring:
 server:
   servlet:
     contextPath: /someapp
   port: 18080
```

The URL-Hint shows
`http://127.0.0.1:18080/stations/{id}`
where it should have been
`http://127.0.0.1:18080/someapp/stations/{id}`
