### ISSUE TITLE
False alarm while validating array in yml files in VS Code?

### ISSUE THREAD

**Issue by brightzheng100** [spring-projects/sts4#17]
Concourse CI Pipeline Editor: Version: 0.0.9-RC.4
VS Code: v1.17.2
OS: Mac

I set the array in `_vars.yml` as below:
```
...
DOCKER_INSECURE_REGISTRIES: [ "10.244.0.8:443" ]
```

And use it in `pipeline.yml` like:
```
resources:
- name: image-XXX
  type: docker-image
  source:
    repository: ((DOCKER_IMAGE))
    insecure_registries: ((DOCKER_INSECURE_REGISTRIES))
    tag: latest
```

But this plugin will complain: `Expecting a 'Sequence' but found a 'Scala'`
After I disabled this plugin, the validation error would be disappeared so it's really caused by it.
