### ISSUE TITLE
The app does not connect to RabbitMQ with Spring cloud stream + rabbitMQ + gradle + STS4.1.0 on Eclipse

### ISSUE THREAD

**Issue by kcschan** [spring-projects/sts4#183]
Description

A spring cloud stream gradle project does not connect to rabbitMQ installed locally, if it is run using the Boot Dashboard provided by STS.
The project is configured to a minimum to test rabbitMQ connectivity only.

However the issue disappears if either of the following conditions is met:
1, Avoid using STS and run the main class(with @SpringBootApplication annotation) directly as Java application.
2, Instead of the gradle, a Maven project with the same springboot starter and code runs without issue no matter STS is involved.

releated configuration:

gradle version: 4.10.2

spring cloud stream + rabbitMQ + gradle project with STS4.1.0.RELEASE on Eclipse IDE 4.10(2018-12, Build id: 20181214-0600)

build.grade:
created with spring initializr

```
buildscript {
	ext {
		springBootVersion = '2.1.2.RELEASE'
......

ext['springCloudVersion'] = 'Greenwich.RC2'

dependencies {
	implementation('org.springframework.boot:spring-boot-starter-amqp')
	implementation('org.springframework.boot:spring-boot-starter-web')
	implementation('org.springframework.cloud:spring-cloud-starter-stream-rabbit')
	implementation('org.springframework.cloud:spring-cloud-stream')
......
}
```

application.yaml:

```
server:
  port: 8080  
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: username
    password: password
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        producer:
          destination: exchange1
          exchangeType: topic
        consumer:
          destination: exchange2
          group: groupname
```
SpringStreamChannel.java

```
public interface SpringStreamChannel {

	public String CONSUMER = "consumer";
	@Input(CONSUMER)
    public SubscribableChannel consumer();

	public String PRODUCER = "producer";
	@Output(PRODUCER)
    public MessageChannel producer();
}
```

MessageProducer.java

```
@EnableBinding(SpringStreamChannel.class)
public class MessageProducer {
    @Resource
    private SpringStreamChannel channel;

    public void produce(String message) {
        channel.producer().send(MessageBuilder.withPayload(message).build());
    }
}
```
MessageConsumer.java

```
@EnableBinding(SpringStreamChannel.class)
public class MessageConsumer {
	
	private Logger log = LoggerFactory.getLogger(getClass());

    @StreamListener(SpringStreamChannel.CONSUMER)
    public void consume(String message){
        log.info("log message:", message);
    }
}
```

Controller
```
@RestController
public class HelloController {

    @Resource
    private MessageProducer producer;

    @GetMapping("/hello")
    public void hello(String message){
        producer.produce(message);
    }
}
```
