### ISSUE TITLE
Concourse extension confused by docker-image resource type

### ISSUE THREAD

**Issue by marco-m** [spring-projects/sts4#196]
Hello,

consider a pipeline beginning with:

```
resource_types:

- name: docker-image
  privileged: true
  type: docker-image
  source:
    repository: concourse/docker-image-resource
```

This seems bizarre at first, on the other hand the repetition of `docker-image` in the `name:` and `type:` is needed, since `docker-image` is a special one.

The stanza above uses the built-in `docker-image` to download this new `docker-image` and use it during the pipeline. Confusing at first but it works :-)

The extension is confused and reports an non existing error:

![duplicate](https://user-images.githubusercontent.com/3075069/52216327-4804f280-2896-11e9-82e9-45ec6872dac1.png)
