### ISSUE TITLE
Concourse extension doesn't know about tag_file for docker-image resource

### ISSUE THREAD

**Issue by marco-m** [spring-projects/sts4#197]
Hello,

consider the following pipeline:

```YAML
resources:

- name: banana-img.git
  type: docker-image
  source:
    repository: repo/banana-scratch-build

- name: repo.git
  type: git
  source:
    uri: https://example.com/repo.git

jobs:

- name: work-img
  plan:

  - get: repo.git
  - put: banana-img.git
    params:
      build: repo.git/img
      tag_prefix: hello
      tag_file: repo.git/img/tag_file

```

the extension says:

```
Unknown property 'tag_file' for type 'DockerImagePutParams'
```

![tag](https://user-images.githubusercontent.com/3075069/52267515-80a9d800-2939-11e9-841d-ae2dfc7b1629.png)
