### ISSUE TITLE
Support icon resource attribute in Concourse Language Server

### ISSUE THREAD

**Issue by jghiloni** [spring-projects/sts4#303]
Concourse 5.x introduced the ability to set an icon on a given resource, specified by giving the name of a Material Design Icon. The language server should support this attribute. I have a PR that I will submit after submitting this issue.

Example:
```
resource:
- name: my-git-repo
  type: git
  icon: github-circle
  source:
    uri: https://github.com/myorg/my-git-repo.git
```
