### ISSUE TITLE
VS Code Extensions missing Cloud Foundry params options

### ISSUE THREAD

**Issue by mjnorman** [spring-projects/sts4#330]
Hello all.  For VSCODE extensions, It does not look like all of the appropriate options are available via intellisense, and errors occur for those not included.  For example including vars results in an error.:

```
  - put: cloud-foundry-g1
    params:
      vars:
        MYVAR: myvalue
      manifest: manifest.yml
```

This looks like where it would need to be added, although my familiarity with VS Code Extensions is limited.

https://github.com/spring-projects/sts4/blob/073d6fa98a5e518e4555440e345546437da9145b/headless-services/concourse-language-server/src/main/java/org/springframework/ide/vscode/concourse/PipelineYmlSchema.java#L736
