### ISSUE TITLE
[concourse] in_parallel - support both array of steps; and explicit "steps" child

### ISSUE THREAD

**Issue by drnic** [spring-projects/sts4#345]
<img width="323" alt="image" src="https://user-images.githubusercontent.com/108/63236715-2a233c00-c282-11e9-9b1f-e1c4b1ea9000.png">

From https://concourse-ci.org/in-parallel-step.html

> `in_parallel: ([step] | config)`

Two forms of configuration are supported. The simplest form is a simple array of other steps, like so:

```yaml
in_parallel:
- get: a
- get: b
```

This is shorthand for the following configuration:

```yaml
in_parallel:
  steps:
  - get: a
  - get: b
```
