### ISSUE TITLE
Concourse extension doesn't know about check_every for a resource type

### ISSUE THREAD

**Issue by marco-m** [spring-projects/sts4#382]
Consider this pipeline snippet:

```yaml
resource_types:

- name: cogito
  type: registry-image
  check_every: 24h          # <=== error reported here
  source:
    repository: ((docker-registry))/cogito
```

The extension wrongly reports

`Unknown property 'check_every' for type 'ResourceType'`

The documentation about `check_every` for resource types is: https://concourse-ci.org/resource-types.html#resource-type-check-every
