### ISSUE TITLE
Concourse extension doesn't know about on_error for jobs

### ISSUE THREAD

**Issue by marco-m** [spring-projects/sts4#383]
Consider the following pipeline:

```
resource_types:

- name: cogito
  type: registry-image
  check_every: 24h
  source:
    repository: ((docker-registry))/cogito

resources:

- name: gh-status
  type: cogito
  check_every: 24h

- name: repo.git
  type: git
  source:
    uri: git@github.com:((github-owner))/((repo-name)).git

jobs:

  - name: autocat
    on_error:                     # <== problem reported here
      put: gh-status
      inputs: [repo.git]
    plan:
      - get: repo.git
        trigger: true
      - put: gh-status
        inputs: [repo.git]
```

The extension wrongly reports for `on_error`:

`Unknown property 'on_error' for type 'Job'`.

The documentation for `on_error` is: https://concourse-ci.org/on-error-step-hook.html#on_error
