### ISSUE TITLE
[vscode-concourse] complains about old_name in a job

### ISSUE THREAD

**Issue by parkeyparker** [spring-projects/sts4#388]
As of Concourse 5.2.0 `old_name` is an optional property for a `job` allowing for the inheritance of job history in the case of a rename. The documentation of this feature can be found [here](https://concourse-ci.org/jobs.html#job-old-name).

The following is a valid example:
```
jobs:
  - name: new-job-name
    old_name: original-job-name
    plan:
      - ...
```

I may try to create a PR for this if I get time as a nice small task
