### ISSUE TITLE
[concourse] Support validation and completions inside `params` of `resource_type`

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/sts4#390]
Example:

```
resource_types:

- name: cogito
  type: registry-image
  check_every: 24h
  params:
    <*>
  source:
    repository: ((docker-registry))/cogito
```

Invoking completions where the cursor `<*>` is should suggest attributes as in the params of a `get` step of a `registry_image` resource. These are documented here: https://github.com/concourse/registry-image-resource#in-fetch-the-images-rootfs-and-metadata

At the moment it only has one valid attribute called `format`

Similarly any attributes below the params should be validated (i.e. at the moment the only valid attribute is `format`.

Related discussion: https://github.com/concourse/docs/issues/273
