### ISSUE TITLE
Concourse CI Pipeline Editor reports errors on valid `pipeline.yml`

### ISSUE THREAD

**Issue by olle-brkt** [spring-projects/sts4#41]
Hi!

I've seen this plug-in report lines that are valid pipeline config. What's interesting is that these pipelines are validating and formatted using `fly format-pipeline` so they should be totally legit.

## pipeline.yml:
Both errors I have found were in the same inline task definition:
```
- task: find-ami
  config:
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: czero/rootfs
    params:
      REGION: ""
    run:
      path: bash
      args:
      - -c
      - |
        ami=$(grep $REGION pivnet-opsmgr/*.yml | cut -d' ' -f2)
        echo $ami > stock-ami/ami
    inputs:
    - name: pivnet-opsmgr
      path: ""
      optional: false
    outputs:
    - name: stock-ami
      path: ""
  params:
    REGION: {{aws_region}}
```

## Errors:
![screen shot 2018-02-20 at 12 00 34](https://user-images.githubusercontent.com/31876997/36446287-b4d0c444-1635-11e8-9223-1d2f1a565174.png)

1. here, the plugin complains the the paths in the input/output sections should not be empty, even though it was set to an empty string by `fly format-pipeline` and it is totally valid to do so (if the sting is empty, the name of the input/output is assumed to be the path)

2. here, the plugin complains about the new 'optional' property introduced in 3.9.0, see https://concourse.ci/running-tasks.html#input-optional

3. is the same as 1

let me know if you need more information!
