### ISSUE TITLE
关于STS运行聚合工程中的web项目

### ISSUE THREAD

**Issue by Xmd-git** [spring-projects/sts4#424]
在聚合工程中，我选中项目后，居然没有run server，不知道怎么回事

**Comment by martinlippert** [comment]
没有更多细节，很难说到底出了什么问题。 您可以附加一个示例项目并描述如何重现所观察到的问题的步骤吗?

(my Chinese language skills are based on Google translate, so be patient with what I wrote here, but independent of that I would prefer to keep the issues in this tracker in English)

**Comment by humphreygao** [comment]
@martinlippert 
I wonder whether Spring Tool suite can support content assist for keys that exist in YAML and properties files.

Take the YAML below as example, if I trigger the content-assist shortcut  `Alt+/` when the cursor is between the curly braces of `${}`, it would be better to provide proposals like `server.port`, `spring.application.name` and `spring.cloud.consul.port`.

```yaml
server:
  port: 8006

spring:
  application:
    name: dadada
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
```
