### ISSUE TITLE
Content assist for keys that exist in YAML and properties files

### ISSUE THREAD

**Issue by humphreygao** [spring-projects/sts4#427]
Take the YAML below as example, if I trigger the content-assist command `Alt+/` when the cursor is between the curly braces of `${}`, it would be better to provide proposals like `server.port`, `spring.application.name`, `spring.cloud.consul.host` and `spring.cloud.consul.port`.

```yaml
server:
  port: 8006

spring:
  application:
    name: dadada
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
```

By the way, I notice that STS4 doesn't have the Quick Fix proposals like Add `@Autowired` to field variable while STS3 has. Was it possible to integrate this feature into STS4?

**Comment by kdvolder** [comment]
This is a good idea. Thanks for the suggestion.

> By the way, I notice that STS4 doesn't have the Quick Fix proposals like Add @Autowired to field variable while STS3 has. Was it possible to integrate this feature into STS4?

I think it is probably possible. But please raise a separate issue to ask for that.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Kris De Volder:) 

I'm putting this on hold for a bit to return to it again at a later time. 

I already created a test case but it isn't passing yet (since still trying to figure out a good way to implement this).

The test case is in branch called `GH_427`.

**Comment by spring-issuemaster** [comment]
(comment in Pivotal Tracker added by Martin Lippert:) 

I tested the implementation and it seems to work fine, but it looks like the content-assist only works for initial values. For example:

```
spring:
  application:
    name: dadada
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spr<*>}
```

works just fine (`<*>` marks the cursor position for content-assist).

But in this case:

```
spring:
  application:
    name: dadada
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.<*>}
```

there is no content-assist showing up. Also this case doesn't show any content-assist:

```
spring:
  application:
    name: dadada
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.app<*>}
```

I think it would be great if the content-assist would show up there, too (as it does in `application.properties` files).
