### ISSUE TITLE
[Concourse] doesn't know about YAML anchors and aliases

### ISSUE THREAD

**Issue by OphyTe** [spring-projects/sts4#482]
The VSCode Concourse CI extension doesn't know about [YAML anchors and aliases](https://yaml.org/spec/1.2/spec.html#id2765878) to navigate into the pipeline.yaml file.

```yaml
services:
  # Node.js gives OS info about the node (Host)
  nodeinfo: &function
    image: functions/nodeinfo:latest
    labels:
      function: "true"
    depends_on:
      - gateway
    networks:
      - functions
    environment:
      no_proxy: "gateway"
      https_proxy: $https_proxy
    deploy:
      placement:
        constraints:
          - 'node.platform.os == linux'
  # Uses `cat` to echo back response, fastest function to execute.
  echoit:
    <<: *function
    image: functions/alpine:health
    environment:
      fprocess: "cat"
      no_proxy: "gateway"
      https_proxy: $https_proxy
```

It should be great if we could go to an alias with Ctrl+click and if anchors were shown in the outline view.
