### ISSUE TITLE
[Concourse] Navigation in pipeline files with VSCode Concourse CI extension doesn't work everytime

### ISSUE THREAD

**Issue by OphyTe** [spring-projects/sts4#483]
Sometimes, navigation through the outline view doesn't work anymore on the pipeline files ... I get the message "No symbols found in document pipeline.yaml' (my document is ok, it works on my Concourse instance). 

I didn't know why yet. Maybe because of my use of yaml anchors and aliases ...

**Comment by kdvolder** [comment]
Does the problem seem deterministic? I.e. is it something that depends on the contents in the editor and allways happens when that editor content is the same? Or is more like something that feels a bit random, it works / doesn't work even though nothing is different about the editor content.

If it is deterministic, it would be very helpful to provide the exact editor content that causes the problem (or a cut down version of it). That should make it relatively easy then to reproduce, diagnose and fix.

**Comment by kdvolder** [comment]
Followed up on your hunch that it might have something to do with anchors and references. And... bingo :-)

This example reproduces the issue:

```
def: &stuff
  name: git
  type: git
  source:
    uri: 
resources:
- <<: *stuff
- name: git2
  type: git
  source:
    uri: git@github.com:kdvolder/7zip.git
```

**Comment by OphyTe** [comment]
Thank you for you answer but it doesn't seems to be so simple.

Indeed, when I delete the lines with anchors or aliases, my outline view doesn't work better.
And on another project I do have a well working outline view for a pipeline.yaml with 1 anchor and 14 aliases ...

Here's a sample:
```yaml
registries-pe: &registries-pe
  insecure_registries:
    - ((docker_pe.registre))
  username: ((docker_pe.utilisateur))
  password: ((docker_pe.mot_de_passe))
  registry_mirror: http://((docker_pe.registre))

resource_types:

  - name: kubernetes-resource
    type: docker-image
    source:
      repository: ((docker_pe.registre))/incubateur/concourse-kubernetes-resource
      tag: 1.16
      <<: *registries-pe

  - name: concourse-pipeline-resource
    type: docker-image
    source:
      repository: ((docker_pe.registre))/concourse/concourse-pipeline-resource
      tag: 1.1.0
      insecure_registries:
        - ((docker_pe.registre))
      <<: *registries-pe
```
