### ISSUE TITLE
skip_download in registry-image ressource is missing

### ISSUE THREAD

**Issue by Clement87** [spring-projects/sts4#523]
The property *skip_download* is missing from the schema of the *registry-image* ressource for *get_params* and *params*.

Error message:
`Unknown property 'skip_download' for type 'RegistryImageGetParams`

Code where *skip_download* is missing:
https://github.com/spring-projects/sts4/commit/0aac76979a7fb6f58f492f63be0bdfc5ae20c2cf#diff-9cd0cd8630bb3b019a1bc5317e378102R596

Code exemple:
```
  - name: docker-base
    type: registry-image
    source:
      repository: alpine
...
        - get: docker-base
          trigger: true
          params:
            skip_download: true
```

```
  - name: docker-app
    type: registry-image
    source:
      repository: privateregistry/myapp
...
      - put: docker-app
        get_params:
          skip_download: true
        params: 
          image: image/image.tar
          additional_tags: tags/tags
```

Thanks

**Comment by kdvolder** [comment]
Thanks for reporting. Just in time... I will try to get a fix in for this before the release which, if all goes as planned should be around the end of this week.

In the future please try to provide a 'complete' example. It is so much more easy to just paste that in an editor to reproduce a problem than it is to take the fragments you provided above, and puzzle it together into an actual complete example.

**Comment by kdvolder** [comment]
Complete example:

```
resources:
- name: docker-base
  type: registry-image
  source:
    repository: alpine
jobs:
- name: publish-jvm-launch-utils
  plan:
  - get: docker-base
    trigger: true
    params:
      skip_download: true
  - put: docker-base
    get_params:
      skip_download: true
    params:
      image: blah
```
