### ISSUE TITLE
[Concourse] Outline view not loaded with VSCode Concourse CI extension when pipeline.yaml not complete

### ISSUE THREAD

**Issue by OphyTe** [spring-projects/sts4#565]
Hi,

I have big pipeline descriptors with a lot of anchors and references which make VSC Concourse extension not work (cf. https://github.com/spring-projects/sts4/issues/483).

In order to navigate easily in my pipeline files, I tried to split these files into several ones (that I merge before load into my Concourse CI instance). But the problem is that the extension doesn't load the outline view anymore. I don't have content assist either by the way...

Here an exemple of a splitted file:

```yaml
- name: deploy
  serial: true
  public: true
  plan:
  - in_parallel:
    - get: git-ci
    - get: metadata
    - get: git-tests
    - get: version-back
      trigger: true
      passed:
      - build
    - get: version-front
      trigger: true
      passed:
      - build

  - task: kustomize update
    file: git-ci/ci/tasks/kustomize/task.yaml
    input_mapping:
      git-ci: git-ci
      version-back: version-back
      version-front: version-front
    output_mapping:
      git-ci: git-ci
      k8s: k8s

  - task: Control
    file: git-ci/ci/tasks/control/task.yaml
    input_mapping:
      to_validate: k8s
      pipeline_data: metadata

  <<: *notifications
```

What's the requirement for the files to be correctly parsed by the extension? Do I have to write every sections (resources, jobs, groups, ...) in order it to work? Do the references have to be resolved in the same file ? Does the yaml only has to be valid?

Thanks for your answer
