### ISSUE TITLE
concourse vs code extension not recognise YAML anchors, references, extend

### ISSUE THREAD

**Issue by chaoyangnz** [spring-projects/sts4#58]
anchor `&` 
reference `*` 
extend `<<`

**Comment by kdvolder** [comment]
I think I know what you mean what you are talking about re 'anchor' and 'reference. But can you please a bit more about 'extend'. What is that exactly?

**Comment by kdvolder** [comment]
Actually.. I found this: https://blog.daemonl.com/2016/02/yaml.html
That seems to explain all three. Adding this link for future reference.

If you have an example pipeline file that uses these features is would be still be welcome. It is allways nice to use a 'real' example as a test case instead of making up something totally artificial by myself.

**Comment by kdvolder** [comment]
> Talk is cheap, show me the code.

Quoting your own moto.... Show me the code... means. Show me your pipeline example please :-)

**Comment by chaoyangnz** [comment]
I anchor a reference:
```
---
dcind: &dcind
  type: docker-image
  source:
    repository: kiwiops/stuff-mem-dcind
    tag: latest
...
```
I got `unknow property 'dcind' for type 'Pipeline'`.

```
- task: deploy-ssp-devint
    privileged: true
    config:
      platform: linux
      image_resource: 
        <<: *dcind
      inputs:
      - name: kms
...
```
Here, I got `Unknow property '<<' for type ImageResource`.
