### ISSUE TITLE
Concourse VSCode Extension: Does not recognize GCS buckets in semver resource

### ISSUE THREAD

**Issue by migs** [spring-projects/sts4#60]
Hi,

I have the following resource defined in my pipeline:

```
resources:
- name: resource-name
  type: semver
  check_every: 1h  
  source:
    driver: gcs
    bucket: bucket-name
    key: version
    json_key: ((gcp.key))
```

This works fine in Concourse, but the VScode plugin shows the following problems:

```
'gcs' is an unknown 'SemverDriver'. Valid values are: [git, s3, swift]
Unknown property 'bucket' for type 'SemverSource'
Unknown property 'key' for type 'SemverSource'
Unknown property 'json_key' for type 'SemverSource'
```

Can this support be enabled? It is documented here: https://github.com/concourse/semver-resource
