### ISSUE TITLE
In application.yml deprecated 'spring.profiles' is not showing a warning

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/sts4#615]
**Describe the bug**
In application.yml deprecated 'spring.profiles' is not showing a warning.

The 'spring.profiles' property is deprecated in spring boot 2.4.x. In properties file it shows a yellow squigly and shows a warning for that. But not in .yml. Some other deprecated properties do show warnings, so not really sure what makes that property 'special'. 

**To Reproduce**

Create a new starter project using spring boot 2.4

In application.yml put:

```
spring:
  profiles: frodod,aaacc
  config:
    activate:
      on-profile:
      - frodood
```

Notice there are no errors or warnings. However if we hover over `profiles` we see that this property is in fact deprecated. So the correct behavior for the editor would be to show a warning for this.
