### ISSUE TITLE
[vscode Concourse extension] Step and properties not recognized

### ISSUE THREAD

**Issue by ThibaultDelaune-pro** [spring-projects/sts4#633]
**Expected Behavior**
Every properties from the current Concourse pipeline descriptor specification should be recognized by the extension.
Including `old_name` on resources (cf. [doc](https://concourse-ci.org/resources.html#schema.resource.old_name)) and `load_var` steps (cf [doc](https://concourse-ci.org/jobs.html#schema.step.load-var-step.load_var)).

**Current Behavior** (with v1.25.1)
If I try to specify an `old_name` on a resource, the extension marks it as an error : `Unknown property 'old_name' for type 'Resource'(YamlSchemaProblem)`.

If I put a `load_var` step, I get the error `Unknown property 'load_var' for type 'Step'(YamlSchemaProblem)` 

**Context**
```yaml
jobs:
  - name: test
    plan:
      - get: my-sources      
      - load_var: test-load
        file: my-sources/test-file

resources:
  - name: my-sources
    old_name: your-sources
    type: git
    source:
      uri: ssh://git@my_repo/my-sources.git
      branch: master
```
