### ISSUE TITLE
[Concourse] VSCode extension doesn't understand glob patterns in group config

### ISSUE THREAD

**Issue by ringods** [spring-projects/sts4#639]
**Describe the bug**
The Concourse extension in VSCode complains on glob patterns in `groups` configuration.

https://concourse-ci.org/pipelines.html#schema.group_config

**To Reproduce**

Use the sample from below. Although incomplete to be used in a real Concourse setup, it shows the error being reported clearly:

<img width="725" alt="Screenshot 2021-05-10 at 08 30 34" src="https://user-images.githubusercontent.com/77923/117615539-24623e00-b16a-11eb-93fe-22f816c60f13.png">

On top of that, the reverse problem of a job not being part of a group is also reported:

<img width="605" alt="Screenshot 2021-05-10 at 08 30 44" src="https://user-images.githubusercontent.com/77923/117615558-2a581f00-b16a-11eb-8e37-bda219a11a8f.png">

**Sample**

```yaml
groups:
- name: build
  jobs:
    - "ci-*"

jobs:
- name: ci-project-one
  plan:
  - task: gradle-build
    file: gradle-build-dcind.yml
```
