### ISSUE TITLE
[vscode Concourse extension] Property 'commit_message' not recognized for semver resources

### ISSUE THREAD

**Issue by ThibaultDelaune-pro** [spring-projects/sts4#655]
**Describe the bug**
The vscode Concourse extension raise an error when a semver resource has a 'commit_message' property set for git driver.

**To Reproduce**
```yaml
resources:
- name: my_resource
  type: semver
  source:
    driver: git
    uri: ((repo_uri))
    private_key: ((private_key))
    branch: master
    file: version.txt
    commit_message: "[skip ci] my commit message"
```

cf. https://github.com/concourse/semver-resource
