### ISSUE TITLE
vscode Concourse extension false positive: Unknown property 'fetch_tags' for type 'GitSource'(YamlSchemaProblem)

### ISSUE THREAD

**Issue by sfuerte** [spring-projects/sts4#668]
**Describe the bug**
Getting the subject error when adding `fetch_tags` to Git repo source

Using standard https://github.com/concourse/git-resource 

while the extension flags an "error", `fly set-pipeline` command runs just fine.

Versions:
```
Concourse CI Pipeline Editor extension - v1.26.0

VS Code - Version: 1.59.0 (Universal)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:14:40.191Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 20.6.0

> fly --version
7.0.0
```

**To Reproduce / Sample**

```
  - name: my-repo
    type: git
    icon: source-merge
    source:
      uri: git@private-github
      branch: main
      private_key: ((repo-key))
      fetch_tags: true
      tag_filter: "*"
```
