### ISSUE TITLE
Add registry_mirror & across as a known properties

### ISSUE THREAD

**Issue by aaron-uk** [spring-projects/sts4#752]
**Describe the bug**

Wrongfully displaying unknown property for resource type RegistryImageSource for `registry_mirror` & DoStep for `across`

**To Reproduce**

check-sonarqube-quality-gate.yml
```yaml
---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cathive/concourse-sonarqube-qualitygate-task
    tag: "latest"
    registry_mirror:
      host: my-registry.com

inputs:
  - name: sonarqube-analysis

run:
  path: /sonarqube-qualitygate-check
  dir: sonarqube-analysis
```

**Sample**

`Unknown property 'registry_mirror' for type 'RegistryImageSource'vscode-concourse(YamlSchemaProblem)`
![Screenshot 2022-04-04 at 17 18 10](https://user-images.githubusercontent.com/64588523/161588823-cbdd373b-89c5-46b7-9d6b-a82d6345a472.png)

`Unknown property 'across' for type 'DoStep'vscode-concourse(YamlSchemaProblem)`
![Screenshot 2022-04-04 at 17 28 57](https://user-images.githubusercontent.com/64588523/161589598-d99121b2-865d-45d9-84b8-418624636e3b.png)

[registry_mirror info from concourse ci resource repo](https://github.com/concourse/registry-image-resource#:~:text=registry_mirror%3A%20Optional.)

[across step info](https://concourse-ci.org/across-step.html#schema.across)
