### ISSUE TITLE
Concourse extension doesn't recognize URL for "registry_mirror" with a docker-image resource

### ISSUE THREAD

**Issue by guillaumBrisard** [spring-projects/sts4#831]
URL for `registry_mirror` is not recognize URL for a docker-image resource

The extension wrongly reports for `registry_mirror: http://docker-dev-virtual.repository.foo.intra`

`Expecting a 'Map' but found a 'Scalar'vscode-concourse(YamlSchemaProblem)`

The documentation about `registry_mirror` for `resource`: https://github.com/concourse/docker-image-resource#source-configuration

**Comment by kdvolder** [comment]
I reproduced the problem with an example like this:

```
resources:
- name: testing
  type: docker-image
  source:
    registry_mirror: whatever
```

It looks like our Schema for that key expects it be something more like a object looking like this:

```
- name: testing
  type: docker-image
  source:
    repository: aaa
    registry_mirror:
      host: somehost.com
      password: aaa
      username: vvv
```

I'm not sure where we got that idea from, but clearly it does not agree with the documentation of the resource so it is a mistake.

Should be easy enough to fix.
