### ISSUE TITLE
[Concourse] Java Redhat extension not recognized in VSCode Concourse CI extension

### ISSUE THREAD

**Issue by ThibaultDelaune-pro** [spring-projects/sts4#924]
**Description**
I'm running the VSCode Concourse CI extension in version 1.41.0-RC.2 and I'm not able to use the outline view or GoTo feature in my pipelines anymore. I get the following message in the "Running Status" tab :
> Extension 'redhat.java' is not known or not activated

However, redhat extension is running (I can navigate into my Java files)

**To Reproduce**
Open a pipeline file and observe the outline view.

**Sample**
```yaml
jobs:
  - name: pipeline-install
    plan:
      - get: git-ci
        trigger: true
      - set_pipeline: self
        file: git-ci/pipeline.yml
resources:
  - name: git-ci
    type: git
    source:
      uri: ssh://git@my-repository.git
```
