### ISSUE TITLE
Add var_sources to Concourse schema

### ISSUE THREAD

**Issue by ThibaultDelaune-pro** [spring-projects/sts4#944]
# Describe the bug

Concourse CI Pipeline Editor VSCode extensions are falsely reporting a problem with `var_sources`.

## Error message:
Unknown property 'var_sources' for type 'Pipeline' _vscode-concourse(YamlSchemaProblem)_

This request is really similar to #942, maybe you could combine them...

# To Reproduce
```yaml
---
var_sources:
- name: global_vars
  type: dummy
  config:
    vars:
      pipeline-path: pipelines/example.yml

resources:
  - name: concourse
    type: git
    icon: github
    source:
      uri: https://github.com/concourse/concourse.git
      branch: main

jobs:
  - name: example
    plan:
      - get: concourse
      - set_pipeline: examples
        file: concourse/((global_vars:pipeline-path))
```

# Fix

Please add `var_sources` to Concourse schema.

cf. https://concourse-ci.org/vars.html#var-sources
