### ISSUE TITLE
Add git-resource submodules param to Concourse schema

### ISSUE THREAD

**Issue by ThibaultDelaune-pro** [spring-projects/sts4#945]
# Describe the bug

Concourse CI Pipeline Editor VSCode extensions are falsely reporting a problem with [git-resource](https://github.com/concourse/git-resource#parameters) `submodules` params.

## Error message:
Unknown property 'submodules' for type 'GitSource' _vscode-concourse(YamlSchemaProblem)_

This request is really similar to #942, maybe you could combine them...

# To Reproduce
```yaml
---
resources:
  - name: concourse
    type: git
    icon: github
    source:
      uri: https://github.com/concourse/concourse.git
      branch: main
    submodules:
    - my-sub-module-path

jobs:
  - name: example
    plan:
      - get: concourse
      - set_pipeline: examples
        file: concourse/pipeline.yaml
```

# Fix

Please add `submodules` git-resources params to Concourse schema.

cf. https://github.com/concourse/git-resource#parameters

**Comment by BoykoAlex** [comment]
@ThibaultDelaune-pro I think it is likely you misusing `submodules`. The property `submodules` belongs to Git GET `params`. This property is defined already there.

Think the correct form is:
```
---
resources:
  - name: concourse
    type: git
    icon: github
    source:
      uri: https://github.com/concourse/concourse.git
      branch: main

jobs:
  - name: example
    plan:
      - get: concourse
        params:
          submodules:
            - my-sub-module-path
      - set_pipeline: examples
        file: concourse/pipeline.yaml
```
