### ISSUE TITLE
Unknown property error shown in application.yml when using java records

### ISSUE THREAD

**Issue by philwebb** [spring-projects/sts4#955]
**Describe the bug**
Given the following classes:

```java
@ConfigurationProperties("application.security")
public record SecurityProperties(List<UserProperties> users) {
	
}
```

```java
public record UserProperties(String name, String password, List<String> roles) {

}
```

and the following `application.yml`

```yaml
application:
  security:
    users:
    - name: "user"
      password: "password"
    - name: "admin"
      password: "secret"
      roles: ["admin"]
```

The `application.yml` editor will show:

`Unknown property 'name' for type 'com.example.security.UserProperties'`

If java classes with `@ConstructorBinding` is used, no problems are identified.

**To Reproduce**
As described above.

**Sample**
https://github.com/philwebb/whats-new-in-spring-boot-3-0
